---
id: Service_Gravatar
name: Service_Gravatar
full: Gravatar client library
description: A library for accessing the Avatar services at gravatar.com.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: true
    role: lead
  -
    name: Gunnar Wrobel
    user: wrobel
    email: p@rdus.de
    active: false
    role: lead
version:
  release: 1.0.2
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Http: ^2
      pear.horde.org/Horde_Url: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
